import {Attraction} from '@/types/attraction';

export const attractionsData: Attraction[] = [
    {
        id: '1',
        title: 'Эйфелева башня',
        description: 'Знаменитая железная башня в центре Парижа',
        createdAt: new Date('2025-03-22T10:30:00Z'),
        rating: 5,
        photoUrl: '/eiffel-tower.jpg',
        location: 'Париж, Франция',
        coordinates: {latitude: 48.8584, longitude: 2.2945},
        status: 'planned',
    },
    {
        id: '2',
        title: 'Колизей',
        description: 'Древний амфитеатр в Риме',
        createdAt: new Date('2025-03-21T15:45:00Z'),
        rating: 4,
        photoUrl: '/colosseum.jpg',
        location: 'Рим, Италия',
        coordinates: {latitude: 41.8902, longitude: 12.4922},
        status: 'visited',
    },
    {
        id: '3',
        title: 'Статуя Свободы',
        description: 'Символ свободы в Нью-Йорке',
        createdAt: new Date('2025-03-20T09:15:00Z'),
        rating: 5,
        photoUrl: '/statue-of-liberty.jpg',
        location: 'Нью-Йорк, США',
        coordinates: {latitude: 40.6892, longitude: -74.0445},
        status: 'planned',
    },
    {
        id: '4',
        title: 'Кремль',
        description: 'Исторический укрепленный комплекс в Москве',
        createdAt: new Date('2025-03-19T14:20:00Z'),
        rating: 4,
        photoUrl: '/kremlin.jpg',
        location: 'Москва, Россия',
        coordinates: {latitude: 55.751244, longitude: 37.617678},
        status: 'visited',
    },
    {
        id: '5',
        title: 'Великая Китайская стена',
        description: 'Массивное оборонительное сооружение',
        createdAt: new Date('2025-03-18T11:10:00Z'),
        rating: 5,
        photoUrl: '/great-wall.jpg',
        location: 'Пекин, Китай',
        coordinates: {latitude: 40.4319, longitude: 116.5704},
        status: 'planned',
    },
    {
        id: '6',
        title: 'Мачу-Пикчу',
        description: 'Древний город инков в горах',
        createdAt: new Date('2025-03-17T16:25:00Z'),
        rating: 5,
        photoUrl: '/machu-picchu.jpg',
        location: 'Куско, Перу',
        coordinates: {latitude: -13.1631, longitude: -72.545},
        status: 'planned',
    },
    {
        id: '7',
        title: 'Биг-Бен',
        description: 'Знаменитая часовая башня в Лондоне',
        createdAt: new Date('2025-03-16T13:35:00Z'),
        rating: 4,
        photoUrl: '/big-ben.jpg',
        location: 'Лондон, Великобритания',
        coordinates: {latitude: 51.5007, longitude: -0.1246},
        status: 'visited',
    },
    {
        id: '8',
        title: 'Пирамиды Гизы',
        description: 'Древние пирамиды фараонов',
        createdAt: new Date('2025-03-15T08:50:00Z'),
        rating: 5,
        photoUrl: '/pyramids.jpg',
        location: 'Гиза, Египет',
        coordinates: {latitude: 29.9792, longitude: 31.1342},
        status: 'planned',
    },
    {
        id: '9',
        title: 'Сиднейская опера',
        description: 'Уникальное здание оперного театра',
        createdAt: new Date('2025-03-14T17:05:00Z'),
        rating: 4,
        photoUrl: '/sydney-opera.jpg',
        location: 'Сидней, Австралия',
        coordinates: {latitude: -33.8568, longitude: 151.2153},
        status: 'planned',
    },
    {
        id: '10',
        title: 'Тадж-Махал',
        description: 'Великолепный мавзолей из белого мрамора',
        createdAt: new Date('2025-03-13T12:40:00Z'),
        rating: 5,
        photoUrl: '/taj-mahal.jpg',
        location: 'Агра, Индия',
        coordinates: {latitude: 27.1751, longitude: 78.0421},
        status: 'visited',
    },
];
